# Generated by Django 3.1.6 on 2021-02-02 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('active', models.BooleanField(blank=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_key_words', models.CharField(blank=True, max_length=255, null=True)),
                ('positioning', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Text Page',
                'verbose_name_plural': 'Text Pages',
            },
        ),
        migrations.CreateModel(
            name='TextPagesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='')),
                ('textpages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link', to='textpages.textpages')),
            ],
        ),
    ]
