# Generated by Django 3.1.3 on 2021-02-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpages',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TextPagesFile',
        ),
    ]
