# Generated by Django 3.1.3 on 2021-02-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textpages', '0002_auto_20210204_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpages',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='textpages',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='textpages',
            name='page_type',
            field=models.CharField(choices=[('about_us', 'About us'), ('terms', 'Terms and conditions'), ('index', 'Home')], default='about_us', max_length=30),
        ),
        migrations.AddField(
            model_name='textpages',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textpages',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
