# Generated by Django 3.1.3 on 2021-02-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textpages', '0003_auto_20210222_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpages',
            name='slug_bg',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textpages',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
