# Generated by Django 3.1.3 on 2021-02-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textpages', '0004_auto_20210222_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpages',
            name='page_type',
            field=models.CharField(choices=[('aboutus', 'About us'), ('terms', 'Terms and conditions'), ('index', 'Home')], default='about_us', max_length=30),
        ),
    ]
