# Generated by Django 3.1.6 on 2021-02-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True)),
                ('link_external_resource', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'External Link',
                'verbose_name_plural': 'External Links',
            },
        ),
    ]
