# Generated by Django 3.1.3 on 2021-02-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externallinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallinks',
            name='short_description_bg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externallinks',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externallinks',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='externallinks',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
