# Generated by Django 3.1.3 on 2021-02-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210202_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='politics',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
