# Generated by Django 3.1.3 on 2021-02-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210204_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politics',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_politics', to='company.Company'),
        ),
    ]
