# Generated by Django 3.1.3 on 2021-02-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20210208_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politics',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='company_politics', to='company.Company'),
        ),
    ]
