# Generated by Django 3.1.3 on 2021-02-08 19:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
