# Generated by Django 3.1.3 on 2021-02-08 19:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20210208_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
