# Generated by Django 3.1.3 on 2021-02-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_auto_20210208_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
