# Generated by Django 3.1.3 on 2021-02-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenu',
            name='link_bg',
            field=models.URLField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='link_en',
            field=models.URLField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
